DROP TABLE orders CASCADE CONSTRAINTS;

CREATE TABLE orders (
                        order_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        order_date TIMESTAMP NOT NULL,
                        customer_id NUMBER(19) NOT NULL,
                        status VARCHAR2(20) NOT NULL,
                        amount NUMBER(15,2) NOT NULL,
                        created_at TIMESTAMP NOT NULL
);

CREATE INDEX idx_orders_order_date
    ON orders (order_date);

CREATE INDEX idx_orders_customer_status
    ON orders (customer_id, status);

CREATE INDEX idx_orders_status
    ON orders (status);